let altura = [];
let sexo = [];
let menores = [];

for (i = 0; i < altura.length; i++) {
    altura[i] < altura[i++];

}
let menores = altura.filter(function(altura)) {
    return altura[i] < altura[i++];
}
console.log(menores);
let maiores = altura.filter(function(altura)) {
    return altura[i] > altura[i++];
}
Médiaalturamulheres
var altura = [];
var sexo = [];
var media = 0;
var mediaTital = 0;
sexoalt[0] = ["masc", 1.75];
sexoalt[1] = ["F", 1.65];
let contador = 0;
for (let i = 0; i < sexoalt.leght; i++) {
    switch: sexoalt[i] = "F";
    mediaTotal = media + altura[i];
    contador = contador + 1;
    console.log(sexoalt[i]);
}
mediaTotal = media / contador;